# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[package]
disabled = true

[aws]
disabled = true

[python]
disabled = true

[git_branch]
symbol = ""

[lua]
disabled = true
