# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

# A minimal left prompt
format = """$character"""

# move the rest of the prompt to the right
right_format = """$all"""

[package]
disabled = true

[aws]
disabled = true

[python]
disabled = true

[git_branch]
symbol = ""

[lua]
disabled = true
    
